# Optimization Task
num_feature_basis_functions: 1
trajectory_duration: 8.0
num_time_steps: 30
publish_trajectory_markers: False
publish_best_trajectory_marker: True


# STOMP 
max_iterations: 10
max_iterations_after_collision_free: 1
max_rollouts: 100
min_rollouts: 30
num_rollouts_per_iteration: 10

# STOMP (optional)
use_noise_adaptation: true
write_to_file: false
use_openmp: false

noise_coefficients:
 - group_name: manipulator_rail
   stddev: [0.3, 1.0, 1.0, 0.8, 0.3, 0.3, 0.3]
   min_stddev: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
   decay:  [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
 - group_name: manipulator
   stddev: [1.2, 1.0, 1.0, 0.8, 0.3, 0.3]
   min_stddev: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
   decay:  [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]

features: 
- class: stomp_moveit_interface/ObstacleAvoidanceFeature
  collision_clearance: 0.02
#- class: stomp_moveit_interface/CollisionFeature
#  report_validity: false # report state validity based on distance field
#  collision_clearance: 0.02
#  debug_collisions: false
#  collision_space:
#    size_x: 8.5 # The X dimension in meters of the volume to represent
#    size_y: 6.0 # The Y dimension in meters of the volume to represent
#    size_z: 4.0 # The Z dimension in meters of the volume to represent
#    origin_x: 0.0 
#    origin_y: 0.0 
#    origin_z: 1.5 
#    resolution: 0.03    
#    collision_tolerance: 0.01
#    max_propagation_distance: 0.1
